baseurl = "/"
languageCode = "en-us"
title = "Spacemen's Club"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
footnotereturnlinkcontents = "↩"
disqusShortname = "yourdiscussshortname"

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Spacemen's Club © 2021"
    custom_css = ["css/theme-override.css"]

# If you want to use Fathom (https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"
